In [1]:
import cv2 as cv
import numpy as np
import mysql.connector
import datetime

#Initialise Camera
vid = cv.VideoCapture(0)
dt=datetime.date.today()
# connecting to the db
mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="",
    database="cisco_thingqbator"
    )
db_cursor1=mydb.cursor()

#Create a cascade classifier object
face_cascade = cv.CascadeClassifier("C:/Users/Ayush/Open CV/haarcascade_frontalface_default.xml")
faces=[]

#No. of frames
nof = 0

#List to store each face, to be done later
face_list=[]

while True:
    #checks if the day hasn't changed or if the month has changed
    now=datetime.date.today()
    if dt.day+1==now.day or dt.day>now.day:
        dt=datetime.date.today()
        face_list=[]
#       add a query to send number of faces to the db
#         HERE

    #check returns bool, frame returns the image
    check, frame = vid.read()
    if not check:
        continue
        
    #Increment number of frames
    nof += 1
    
    #Convert image to grayscale
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    
    #Detect multiple faces. Returns a list of faces in the current frame.
    faces = face_cascade.detectMultiScale(gray, 1.5, 5)
    
    #Sort the faces in decreasing order on basis of features
    faces = sorted(faces, key=lambda x: x[2]*x[3], reverse=True)
    
    #Draw a rectangle around each face
    for top, left, bottom, right in faces:
        gray = cv.rectangle(gray, (top, left), (top+bottom, left+right), (0,255,0), 1)
        
    
    #Process only if faces is not empty
    if len(faces)!=0:
        for face in faces[:1]:
            x, y, w, h = face
            
            # Get the face ROI(region of interest)
            offset = 7
            face_section = gray[y-offset:y+h+offset, x-offset:x+w+offset]
            face_section = cv.resize(face_section, (100, 100))
            
            #Append the ROI in the list after every 10 frames
            if nof % 10 == 0:
                face_list.append(face_section)
        
        
    #Show the faces with rectangle drawn on them
    cv.imshow("Face", gray)
    
    #Wait for 1ms per frame. Quit if 'q' pressed.
    key = cv.waitKey(1)
    if key == ord('q'):
        break
    
#Print no. of frames
print(nof)
for i in face_list:
    print(i)
vid.release()
cv.destroyAllWindows()


358
[[175 133 113 ...  99  99  97]
 [177 146 119 ...  93  93  92]
 [178 162 122 ...  88  89  86]
 ...
 [107  88  48 ...  38  57  62]
 [ 98  83  42 ...  39  55  59]
 [ 98  84  43 ...  36  49  54]]
[[129 117 110 ... 104 104 102]
 [144 120 112 ... 101 100  97]
 [159 124 117 ...  94  95  92]
 ...
 [ 62  88  88 ...  35  50  62]
 [ 75  88  84 ...  36  51  64]
 [ 88  87  80 ...  33  47  53]]
[[195 191 155 ... 107 108 107]
 [195 188 170 ... 106 106 106]
 [195 188 177 ... 104 102 102]
 ...
 [ 30  97 107 ...  34  46  68]
 [ 37 103 101 ...  34  48  67]
 [ 47 104  96 ...  32  46  60]]
[[201 201 201 ... 115 117 115]
 [201 201 201 ... 115 114 115]
 [199 201 200 ... 114 114 116]
 ...
 [ 90 112 110 ...  20  26  42]
 [101 131  92 ...  21  22  28]
 [118 144  64 ...  21  22  26]]
[[198 198 199 ... 110 110 110]
 [197 198 198 ... 110 110 108]
 [197 198 198 ... 109 108 106]
 ...
 [ 81 120  37 ...  21  29  49]
 [ 96 125  25 ...  21  25  43]
 [110 121  30 ...  20  22  28]]
[[201 201 202 ... 109 110 109]
 [201